title: Moleculer - Progressive microservices framework for Node.js
subtitle: "Progressive microservices framework for Node.js"
description: "Moleculer is a progressive microservices framework powered by Node.js"
author: MoleculerJS
language: en
timezone: UTC
url: https://moleculer.services
github_edit_link: https://github.com/moleculerjs/site/edit/master/source/
root: /
permalink: news/:year/:month/:day/:title/
#archive_dir: news
code_dir: downloads/code
#new_post_name: :year-:month-:day-:title.md # File name of new posts
#post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: moleculer
# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

#deploy:
#  type: git
#  repo: git@github.com:moleculerjs/moleculerjs.github.io.git

# disqus_shortname: moleculer
google_analytics: UA-99099811-1
# fb_admins: 100000247608790
algolia:
  en:
    api_key: xyz
    index_name: moleculer_web

twitter: MoleculerJS
github: moleculerjs/moleculer

alias:
  docs/benchmark.html: docs/0.12/benchmark.html
  docs/broker.html: docs/0.12/broker.html
  docs/cachers.html: docs/0.12/cachers.html
  docs/circuit-breaker.html: docs/0.12/circuit-breaker.html
  docs/context.html: docs/0.12/context.html
  docs/contributing.html: docs/0.12/contributing.html
  docs/docker.html: docs/0.12/docker.html
  docs/errors.html: docs/0.12/errors.html
  docs/examples.html: docs/0.12/examples.html
  docs/faq.html: docs/0.12/faq.html
  docs/logger.html: docs/0.12/logger.html
  docs/metrics.html: docs/0.12/metrics.html
  docs/modules.html: docs/0.12/modules.html
  docs/moleculer-cli.html: docs/0.12/moleculer-cli.html
  docs/moleculer-repl.html: docs/0.12/moleculer-repl.html
  docs/moleculer-web.html: docs/0.12/moleculer-web.html
  docs/nodes.html: docs/0.12/nodes.html
  docs/runner.html: docs/0.12/runner.html
  docs/serializers.html: docs/0.12/serializers.html
  docs/serverless.html: docs/0.12/serverless.html
  docs/service-registry.html: docs/0.12/service-registry.html
  docs/service.html: docs/0.12/service.html
  docs/statistics.html: docs/0.12/statistics.html
  docs/support.html: support.html
  docs/transporters.html: docs/0.12/transporters.html
  docs/usage.html: docs/0.12/usage.html
  docs/validation.html: docs/0.12/validation.html

  0.12/docs/support.html: support.html

  api/context.html: api/0.12/context.html
  api/protocol.html: api/0.12/protocol.html
  api/service-broker.html: api/0.12/service-broker.html
  api/service.html: api/0.12/service.html

  docs/index.html: docs/0.13/index.html
  api/index.html: docs/0.13/index.html